import { ComponentType } from '@angular/cdk/portal';

import { NgxFormInputs } from '../ngx-form.interface';

import { InputMethods } from './input.interface';
import {
    InputAutoCompleteComponent,
    InputAutoCompleteMethods,
    InputBankCardComponent,
    InputBankCardMethods,
    InputBankShebaComponent,
    InputBankShebaMethods,
    InputCheckboxComponent,
    InputCheckboxMethods,
    InputColorComponent,
    InputColorMethods,
    InputComponentComponent,
    InputComponentMethods,
    InputCoordinatesComponent,
    InputCoordinatesMethods,
    InputDateComponent,
    InputDateMethods,
    InputEmailComponent,
    InputEmailMethods,
    InputFileComponent,
    InputFileMethods,
    InputIconComponent,
    InputIconMethods,
    InputIpComponent,
    InputIpMethods,
    InputItemListComponent,
    InputItemListMethods,
    InputMobileComponent,
    InputMobileMethods,
    InputMomentComponent,
    InputMomentMethods,
    InputMultiSelectComponent,
    InputMultiSelectMethods,
    InputNameComponent,
    InputNameMethods,
    InputNumberComponent,
    InputNumberMethods,
    InputOptionListComponent,
    InputOptionListMethods,
    InputPasswordComponent,
    InputPasswordMethods,
    InputPriceComponent,
    InputPriceMethods,
    InputRouteComponent,
    InputRouteMethods,
    InputSelectComponent,
    InputSelectMethods,
    InputTagComponent,
    InputTagMethods,
    InputTextareaComponent,
    InputTextareaMethods,
    InputTextComponent,
    InputTextMethods,
    InputUrlComponent,
    InputUrlMethods,
    InputUsernameComponent,
    InputUsernameMethods,
} from '.';

export const InputInfo: {
    [key in NgxFormInputs['type']]: {
        readonly title: string;
        readonly methods: InputMethods<any, any>;
        readonly component: ComponentType<any>;
    };
} = {
    'AUTO-COMPLETE': {
        title: 'لیست تکمیلی',
        methods: new InputAutoCompleteMethods(),
        component: InputAutoCompleteComponent,
    },
    'BANK-CARD': { title: 'شماره کارت بانکی', methods: new InputBankCardMethods(), component: InputBankCardComponent },
    'BANK-SHEBA': { title: 'شماره شبا', methods: new InputBankShebaMethods(), component: InputBankShebaComponent },
    CHECKBOX: { title: 'یک انتخابی', methods: new InputCheckboxMethods(), component: InputCheckboxComponent },
    COLOR: { title: 'رنگ', methods: new InputColorMethods(), component: InputColorComponent },
    COMPONENT: { title: 'کامپوننت', methods: new InputComponentMethods(), component: InputComponentComponent },
    COORDINATES: { title: 'موقعیت جغرافیایی', methods: new InputCoordinatesMethods(), component: InputCoordinatesComponent },
    DATE: { title: 'تاریخ', methods: new InputDateMethods(), component: InputDateComponent },
    EMAIL: { title: 'ایمیل', methods: new InputEmailMethods(), component: InputEmailComponent },
    FILE: { title: 'فایل', methods: new InputFileMethods(), component: InputFileComponent },
    ICON: { title: 'آیکون', methods: new InputIconMethods(), component: InputIconComponent },
    IP: { title: 'آدرس آی‌پی', methods: new InputIpMethods(), component: InputIpComponent },
    'ITEM-LIST': { title: 'لیست مقادیر', methods: new InputItemListMethods(), component: InputItemListComponent },
    MOBILE: { title: 'موبایل', methods: new InputMobileMethods(), component: InputMobileComponent },
    MOMENT: { title: 'زمان', methods: new InputMomentMethods(), component: InputMomentComponent },
    'MULTI-SELECT': { title: 'چند انتخابی', methods: new InputMultiSelectMethods(), component: InputMultiSelectComponent },
    NAME: { title: 'نام و نام خانوادگی', methods: new InputNameMethods(), component: InputNameComponent },
    NUMBER: { title: 'مقدار عددی', methods: new InputNumberMethods(), component: InputNumberComponent },
    'OPTION-LIST': { title: 'لیست گزینه‌ها', methods: new InputOptionListMethods(), component: InputOptionListComponent },
    PASSWORD: { title: 'کلمه عبور', methods: new InputPasswordMethods(), component: InputPasswordComponent },
    PRICE: { title: 'قیمت', methods: new InputPriceMethods(), component: InputPriceComponent },
    ROUTE: { title: 'مسیر', methods: new InputRouteMethods(), component: InputRouteComponent },
    SELECT: { title: 'لیست کشویی', methods: new InputSelectMethods(), component: InputSelectComponent },
    TAG: { title: 'تگ', methods: new InputTagMethods(), component: InputTagComponent },
    TEXT: { title: 'متن یک خطی', methods: new InputTextMethods(), component: InputTextComponent },
    TEXTAREA: { title: 'متن چند خطی', methods: new InputTextareaMethods(), component: InputTextareaComponent },
    URL: { title: 'آدرس سایت', methods: new InputUrlMethods(), component: InputUrlComponent },
    USERNAME: { title: 'نام کاربری', methods: new InputUsernameMethods(), component: InputUsernameComponent },
};
